# -*- coding: utf-8 -*-
"""Lab2GANCreation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VzY4NvSb8kxYMgNm8P_UOJNfMb5jFsMc
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import numpy as np

# --- Configuration ---
batch_size = 64
lr = 0.0002
z_dim = 100
image_dim = 28 * 28
epochs = 50
device = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Training on: {device}")

# --- 1. Data Preparation ---
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,)) # Normalize to [-1, 1]
])

dataset = datasets.MNIST(root="dataset/", transform=transform, download=True)
loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# --- 2. Define Models ---
class Generator(nn.Module):
    def __init__(self):
        super().__init__()
        self.gen = nn.Sequential(
            nn.Linear(z_dim, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 1024),
            nn.LeakyReLU(0.2),
            nn.Linear(1024, image_dim),
            nn.Tanh()
        )
    def forward(self, x): return self.gen(x)

class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()
        self.disc = nn.Sequential(
            nn.Linear(image_dim, 512),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3),
            nn.Linear(512, 128),
            nn.LeakyReLU(0.2),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )
    def forward(self, x): return self.disc(x)

# Initialize
gen = Generator().to(device)
disc = Discriminator().to(device)
opt_gen = optim.Adam(gen.parameters(), lr=lr)
opt_disc = optim.Adam(disc.parameters(), lr=lr)
criterion = nn.BCELoss()

# --- Helper: Get Weight Norms ---
def get_model_params(model):
    return torch.cat([p.view(-1) for p in model.parameters()]).detach().clone()

# --- Helper: Visualize Images ---
def visualize_results(epoch):
    gen.eval() # Switch to evaluation mode
    with torch.no_grad():
        # Generate 16 fake images
        noise = torch.randn(16, z_dim).to(device)
        fake_images = gen(noise).reshape(-1, 28, 28).cpu()

        # Plotting
        plt.figure(figsize=(6, 6))
        for i in range(16):
            plt.subplot(4, 4, i+1)
            plt.imshow(fake_images[i], cmap='gray')
            plt.axis('off')
        plt.suptitle(f"Generated Images at Epoch {epoch}")
        plt.show() # If using a script, you might want plt.savefig(f"epoch_{epoch}.png")
    gen.train() # Switch back to training mode

# --- 3. Training Loop ---
for epoch in range(epochs):
    total_d_diff = 0
    total_g_diff = 0
    num_batches = len(loader)

    for batch_idx, (real, _) in enumerate(loader):
        real = real.view(-1, 784).to(device)
        batch_size = real.shape[0]

        # --- Train Discriminator ---
        noise = torch.randn(batch_size, z_dim).to(device)
        fake = gen(noise)

        disc_real = disc(real).view(-1)
        lossD_real = criterion(disc_real, torch.ones_like(disc_real))

        disc_fake = disc(fake.detach()).view(-1)
        lossD_fake = criterion(disc_fake, torch.zeros_like(disc_fake))

        lossD = (lossD_real + lossD_fake) / 2

        disc.zero_grad()
        lossD.backward()
        params_d_before = get_model_params(disc) # Track weights
        opt_disc.step()
        params_d_after = get_model_params(disc)  # Track weights
        total_d_diff += torch.norm(params_d_after - params_d_before).item()

        # --- Train Generator ---
        output = disc(fake).view(-1)
        lossG = criterion(output, torch.ones_like(output))

        gen.zero_grad()
        lossG.backward()
        params_g_before = get_model_params(gen) # Track weights
        opt_gen.step()
        params_g_after = get_model_params(gen)  # Track weights
        total_g_diff += torch.norm(params_g_after - params_g_before).item()

    # --- End of Epoch Stats ---
    avg_d_diff = total_d_diff / num_batches
    avg_g_diff = total_g_diff / num_batches

    print(f"Epoch [{epoch}/{epochs}] "
          f"Loss D: {lossD:.4f} | Loss G: {lossG:.4f} | "
          f"D_Delta: {avg_d_diff:.5f} | G_Delta: {avg_g_diff:.5f}")

    # --- Visualize every 5 or 10 epochs ---
    if epoch % 5 == 0:
        visualize_results(epoch)