# -*- coding: utf-8 -*-
"""LAB2Fashion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYHOX3yVTDkgBKBW3JNCq-55ougMw5dN
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import numpy as np
import os

config = {
    'epochs': 60,
    'batch_size': 64,
    'noise_dim': 100,
    'learning_rate': 0.0002,
    'save_interval': 5
}

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Running Fashion-MNIST GAN on: {device}")

os.makedirs("generated_samples", exist_ok=True)
os.makedirs("final_generated_images", exist_ok=True)

# 2. LOAD DATA
# ==========================================
print("\nLoading Fashion-MNIST dataset...")
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

dataset = datasets.FashionMNIST(root="./data", train=True, transform=transform, download=True)
dataloader = DataLoader(dataset, batch_size=config['batch_size'], shuffle=True)

label_map = {
    0: 'T-shirt/top', 1: 'Trouser', 2: 'Pullover', 3: 'Dress', 4: 'Coat',
    5: 'Sandal', 6: 'Shirt', 7: 'Sneaker', 8: 'Bag', 9: 'Ankle boot'
}

# 3. HELPER: ROBUST CLASSIFIER (Improved)
# ==========================================
class RobustClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        # Deeper architecture: 32 -> 64 filters
        self.features = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(2), # 28x28 -> 14x14

            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(2), # 14x14 -> 7x7
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 7 * 7, 128),
            nn.ReLU(),
            nn.Dropout(0.5), # Prevents overfitting
            nn.Linear(128, 10)
        )

    def forward(self, x):
        x = self.features(x)
        return self.classifier(x)

def prepare_classifier():
    print("Training robust classifier for evaluation (Wait ~1-2 mins)...")
    clf = RobustClassifier().to(device)
    opt = optim.Adam(clf.parameters(), lr=0.001)
    crit = nn.CrossEntropyLoss()

    # Train for 5 full epochs (instead of partial 1) to ensure high accuracy
    clf.train()
    for epoch in range(10):
        correct = 0
        total = 0
        running_loss = 0.0

        for images, labels in dataloader:
            images, labels = images.to(device), labels.to(device)

            opt.zero_grad()
            outputs = clf(images)
            loss = crit(outputs, labels)
            loss.backward()
            opt.step()

            # Track accuracy
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
            running_loss += loss.item()

        acc = 100 * correct / total
        print(f"  Classifier Epoch {epoch+1}/10 | Loss: {running_loss/len(dataloader):.4f} | Acc: {acc:.2f}%")

    print("Classifier ready.\n")
    clf.eval()
    return clf

# Replace the old call with this new one
classifier = prepare_classifier()

# 4. GAN ARCHITECTURE
# ==========================================
class Generator(nn.Module):
    def __init__(self, noise_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(noise_dim, 256), nn.LeakyReLU(0.2), nn.BatchNorm1d(256),
            nn.Linear(256, 512), nn.LeakyReLU(0.2), nn.BatchNorm1d(512),
            nn.Linear(512, 1024), nn.LeakyReLU(0.2), nn.BatchNorm1d(1024),
            nn.Linear(1024, 28*28), nn.Tanh()
        )
    def forward(self, x): return self.net(x).view(-1, 1, 28, 28)

class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Flatten(),
            nn.Linear(28*28, 512), nn.LeakyReLU(0.2), nn.Dropout(0.3),
            nn.Linear(512, 256), nn.LeakyReLU(0.2), nn.Dropout(0.3),
            nn.Linear(256, 1), nn.Sigmoid()
        )
    def forward(self, x): return self.net(x)

gen = Generator(config['noise_dim']).to(device)
disc = Discriminator().to(device)
opt_g = optim.Adam(gen.parameters(), lr=config['learning_rate'], betas=(0.5, 0.999))
opt_d = optim.Adam(disc.parameters(), lr=config['learning_rate'], betas=(0.5, 0.999))
criterion = nn.BCELoss()

# Helper for Weight Delta
def get_params(model):
    return torch.cat([p.view(-1) for p in model.parameters()]).detach().clone()

# Helper for Visualization
def show_and_save_images(epoch, fixed_noise):
    gen.eval()
    with torch.no_grad():
        fake_imgs = gen(fixed_noise).cpu()

    # Create figure
    fig, axes = plt.subplots(5, 5, figsize=(6, 6))
    plt.suptitle(f"Epoch {epoch}")

    for i, ax in enumerate(axes.flatten()):
        ax.imshow(fake_imgs[i].squeeze(), cmap='gray')
        ax.axis('off')

    # 1. Save to folder
    save_path = f"generated_samples/epoch_{epoch:02d}.png"
    plt.savefig(save_path)

    # 2. Show in notebook/console
    plt.show()

    print(f"Saved image to: {save_path}")
    gen.train()

print(f"\nStarting GAN Training ({config['epochs']} Epochs)...")
fixed_noise = torch.randn(25, config['noise_dim']).to(device)

for epoch in range(config['epochs']):
    d_loss_sum = 0; g_loss_sum = 0; d_acc_sum = 0
    d_delta_sum = 0; g_delta_sum = 0
    batches = 0

    for real_imgs, _ in dataloader:
        real_imgs = real_imgs.to(device)
        curr_batch = real_imgs.size(0)

        # --- TRAIN D ---
        disc.zero_grad()
        out_real = disc(real_imgs)
        loss_real = criterion(out_real, torch.ones_like(out_real))

        noise = torch.randn(curr_batch, config['noise_dim']).to(device)
        fake_imgs = gen(noise)
        out_fake = disc(fake_imgs.detach())
        loss_fake = criterion(out_fake, torch.zeros_like(out_fake))

        loss_d = (loss_real + loss_fake) / 2
        loss_d.backward()
        p_d_before = get_params(disc)
        opt_d.step()
        p_d_after = get_params(disc)
        d_delta_sum += torch.norm(p_d_after - p_d_before).item()

        d_acc = ((out_real > 0.5).float().mean() + (out_fake < 0.5).float().mean()) / 2

        # --- TRAIN G ---
        gen.zero_grad()
        out_g = disc(fake_imgs)
        loss_g = criterion(out_g, torch.ones_like(out_g))
        loss_g.backward()
        p_g_before = get_params(gen)
        opt_g.step()
        p_g_after = get_params(gen)
        g_delta_sum += torch.norm(p_g_after - p_g_before).item()

        d_loss_sum += loss_d.item(); g_loss_sum += loss_g.item()
        d_acc_sum += d_acc.item(); batches += 1

    # --- LOGS ---
    print(f"Epoch {epoch+1:02d}/{config['epochs']} | "
          f"Loss D: {d_loss_sum/batches:.4f} | D Acc: {100*d_acc_sum/batches:.2f}% | "
          f"Loss G: {g_loss_sum/batches:.4f} | "
          f"D_Delta: {d_delta_sum/batches:.5f} | G_Delta: {g_delta_sum/batches:.5f}")

    # --- SHOW & SAVE ---
    if (epoch + 1) % config['save_interval'] == 0:
        show_and_save_images(epoch+1, fixed_noise)

# 6. FINAL REPORT
# ==========================================
print("\nGenerating Final Report...")
gen.eval()
with torch.no_grad():
    final_noise = torch.randn(100, config['noise_dim']).to(device)
    final_imgs = gen(final_noise)

    # Predict
    out = classifier(final_imgs)
    _, preds = torch.max(out, 1)
    preds = preds.cpu().numpy()

# Save Master Grid
fig, axes = plt.subplots(10, 10, figsize=(10, 10))
for i, ax in enumerate(axes.flatten()):
    ax.imshow(final_imgs[i].cpu().squeeze(), cmap='gray')
    ax.axis('off')
plt.savefig("final_generated_images/final_grid.png")
plt.show()

print("\n--- Synthetic Image Distribution ---")
unique, counts = np.unique(preds, return_counts=True)
for label, count in zip(unique, counts):
    print(f"Class {label} ({label_map[label]}): {count} images")

import torch
import matplotlib.pyplot as plt
import numpy as np
import os
import datetime

# ==========================================
# FINAL REPORT GENERATION (No Training)
# ==========================================

# 1. Define the Label Map (Matches your output)
label_map = {
    0: 'T-shirt/top',
    1: 'Trouser',
    2: 'Pullover',
    3: 'Dress',
    4: 'Coat',
    5: 'Sandal',
    6: 'Shirt',
    7: 'Sneaker',
    8: 'Bag',
    9: 'Ankle boot'
}

print("Generating Final Report from current model...")

# 2. Generate 100 Fake Images
gen.eval()
with torch.no_grad():
    # Create 100 random noise vectors
    final_noise = torch.randn(100, config['noise_dim']).to(device)

    # Generate images
    final_imgs = gen(final_noise)

    # Predict labels using the pre-trained classifier
    outputs = classifier(final_imgs)
    _, preds = torch.max(outputs, 1)
    preds = preds.cpu().numpy()

# 3. Create and Save Master Grid (10x10)
grid_path = "final_generated_images/final_grid.png"
fig, axes = plt.subplots(10, 10, figsize=(10, 10))

for i, ax in enumerate(axes.flatten()):
    # Convert from [-1, 1] to [0, 1] for display if needed,
    # but imshow handles range well usually.
    img = final_imgs[i].cpu().squeeze()
    ax.imshow(img, cmap='gray')
    ax.axis('off')

plt.suptitle("Final Generated Batch (100 Samples)")
plt.tight_layout()
plt.savefig(grid_path)
plt.show()
plt.close()

# 4. Generate Text Report Content
unique, counts = np.unique(preds, return_counts=True)
distribution_str = ""

for label, count in zip(unique, counts):
    label_name = label_map.get(label, "Unknown")
    distribution_str += f"Class {label} ({label_name}): {count} images\n"

# Use final stats if available in memory, otherwise defaults
d_loss = final_stats['loss_d'] if 'final_stats' in locals() else 0.0
g_loss = final_stats['loss_g'] if 'final_stats' in locals() else 0.0
d_acc  = final_stats['acc_d']  if 'final_stats' in locals() else 0.0

report_content = f"""
==================================================
GAN TRAINING REPORT (Fashion-MNIST)
==================================================
Date: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Device: {device}

1. CONFIGURATION
----------------
- Epochs: {config['epochs']}
- Batch Size: {config['batch_size']}
- Noise Dimension: {config['noise_dim']}
- Learning Rate: {config['learning_rate']}

2. FINAL METRICS (Last Epoch)
--------------------------------------------------
- Discriminator Loss: {d_loss:.4f}
- Generator Loss:     {g_loss:.4f}
- Discriminator Acc:  {d_acc:.2f}%

3. GENERATED IMAGE ANALYSIS (Sample Size: 100)
--------------------------------------------------
The pre-trained classifier detected the following
distribution in the synthetic batch:

{distribution_str}

4. OUTPUT FILES
----------------
- Image Grid: {grid_path}
- Report Log: gan_training_report.txt
==================================================
"""

# 5. Write Report to Disk
report_path = "gan_training_report.txt"
with open(report_path, "w") as f:
    f.write(report_content)

print(report_content)
print(f"\n[SUCCESS] Report saved locally to: {report_path}")

# ==========================================
# 6. TRIGGER DOWNLOAD (Colab/Jupyter)
# ==========================================
try:
    from google.colab import files
    print("Triggering browser download...")
    files.download(report_path)
    files.download(grid_path)
except ImportError:
    print("(Files are saved in your folder)")