# -*- coding: utf-8 -*-
"""LAB6GenAi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uonstwuo7Bt1nMb0cF5X4uwzw1PL2vhX
"""

!pip install -q torch torchvision matplotlib numpy Pillow tqdm

import os, time, random
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
from torch.utils.data import Dataset, DataLoader

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')
if torch.cuda.is_available():
    print(f'GPU: {torch.cuda.get_device_name(0)}')

DATA_DIR = './edges2shoes'

if not os.path.exists(DATA_DIR):
    print('Downloading Edges2Shoes...')
    !wget -q --show-progress -O edges2shoes.tar.gz http://efrosgans.eecs.berkeley.edu/pix2pix/datasets/edges2shoes.tar.gz
    !tar -xzf edges2shoes.tar.gz
    !rm edges2shoes.tar.gz
    print('Done.')
else:
    print('Already exists.')

for split in ['train', 'val']:
    path = os.path.join(DATA_DIR, split)
    if os.path.exists(path):
        print(f'{split}: {len(os.listdir(path))} images')

IMG_SIZE    = 256
BATCH_SIZE  = 8
EPOCHS      = 50
LR          = 0.0002
BETA1       = 0.5
LAMBDA_L1   = 100.0
TRAIN_LIMIT = 1000
VAL_LIMIT   = 100

class Edges2ShoesDataset(Dataset):
    def __init__(self, root_dir, split='train', img_size=256, limit=None):
        self.root_dir = os.path.join(root_dir, split)
        self.files = sorted([f for f in os.listdir(self.root_dir)
                             if f.lower().endswith(('.jpg','.png','.jpeg'))])
        if limit:
            self.files = self.files[:limit]
        self.transform = transforms.Compose([
            transforms.Resize((img_size, img_size)),
            transforms.ToTensor(),
            transforms.Normalize([0.5]*3, [0.5]*3)
        ])

    def __len__(self): return len(self.files)

    def __getitem__(self, idx):
        img = Image.open(os.path.join(self.root_dir, self.files[idx])).convert('RGB')
        w, h = img.size; half = w // 2
        edge = img.crop((0, 0, half, h))
        real = img.crop((half, 0, w, h))
        return self.transform(edge), self.transform(real)

train_ds = Edges2ShoesDataset(DATA_DIR, 'train', IMG_SIZE, TRAIN_LIMIT)
val_ds   = Edges2ShoesDataset(DATA_DIR, 'val',   IMG_SIZE, VAL_LIMIT)
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=2)
val_loader   = DataLoader(val_ds,   batch_size=4,          shuffle=False, num_workers=2)

print(f'Train: {len(train_ds)} | Val: {len(val_ds)}')

# UNET generator

class UNetDown(nn.Module):
    def __init__(self, in_ch, out_ch, normalize=True, dropout=0.0):
        super().__init__()
        layers = [nn.Conv2d(in_ch, out_ch, 4, stride=2, padding=1, bias=False)]
        if normalize: layers.append(nn.BatchNorm2d(out_ch))
        layers.append(nn.LeakyReLU(0.2, inplace=True))
        if dropout: layers.append(nn.Dropout(dropout))
        self.model = nn.Sequential(*layers)
    def forward(self, x): return self.model(x)

class UNetUp(nn.Module):
    def __init__(self, in_ch, out_ch, dropout=0.0):
        super().__init__()
        layers = [
            nn.ConvTranspose2d(in_ch, out_ch, 4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(out_ch), nn.ReLU(inplace=True)
        ]
        if dropout: layers.append(nn.Dropout(dropout))
        self.model = nn.Sequential(*layers)
    def forward(self, x, skip):
        return torch.cat([self.model(x), skip], dim=1)

class UNetGenerator(nn.Module):
    def __init__(self, in_ch=3, out_ch=3):
        super().__init__()
        self.d1 = UNetDown(in_ch,  64,  normalize=False)
        self.d2 = UNetDown(64,  128)
        self.d3 = UNetDown(128, 256)
        self.d4 = UNetDown(256, 512)
        self.d5 = UNetDown(512, 512)
        self.d6 = UNetDown(512, 512)
        self.d7 = UNetDown(512, 512)
        self.d8 = UNetDown(512, 512, normalize=False)

        self.u1 = UNetUp(512,  512, dropout=0.5)
        self.u2 = UNetUp(1024, 512, dropout=0.5)
        self.u3 = UNetUp(1024, 512, dropout=0.5)
        self.u4 = UNetUp(1024, 512)
        self.u5 = UNetUp(1024, 256)
        self.u6 = UNetUp(512,  128)
        self.u7 = UNetUp(256,   64)
        self.final = nn.Sequential(
            nn.ConvTranspose2d(128, out_ch, 4, stride=2, padding=1), nn.Tanh()
        )

    def forward(self, x):
        d1=self.d1(x); d2=self.d2(d1); d3=self.d3(d2); d4=self.d4(d3)
        d5=self.d5(d4); d6=self.d6(d5); d7=self.d7(d6); d8=self.d8(d7)
        u1=self.u1(d8,d7); u2=self.u2(u1,d6); u3=self.u3(u2,d5); u4=self.u4(u3,d4)
        u5=self.u5(u4,d3); u6=self.u6(u5,d2); u7=self.u7(u6,d1)
        return self.final(u7)

print('U-Net Generator ready.')

# patchgan discriminator


class PatchGANDiscriminator(nn.Module):
    def __init__(self, in_ch=6):
        super().__init__()
        def block(ic, oc, norm=True):
            layers = [nn.Conv2d(ic, oc, 4, stride=2, padding=1)]
            if norm: layers.append(nn.BatchNorm2d(oc))
            layers.append(nn.LeakyReLU(0.2, inplace=True))
            return layers
        self.model = nn.Sequential(
            *block(in_ch,  64, norm=False),
            *block(64,  128),
            *block(128, 256),
            nn.Conv2d(256, 512, 4, stride=1, padding=1),
            nn.BatchNorm2d(512), nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(512, 1, 4, stride=1, padding=1)
        )
    def forward(self, condition, image):
        return self.model(torch.cat([condition, image], dim=1))

print('PatchGAN Discriminator ready.')

# baseline CNN

class BaselineCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Conv2d(3,   64,  4, stride=2, padding=1), nn.LeakyReLU(0.2, True),
            nn.Conv2d(64,  128, 4, stride=2, padding=1), nn.BatchNorm2d(128), nn.LeakyReLU(0.2, True),
            nn.Conv2d(128, 256, 4, stride=2, padding=1), nn.BatchNorm2d(256), nn.LeakyReLU(0.2, True),
            nn.Conv2d(256, 512, 4, stride=2, padding=1), nn.BatchNorm2d(512), nn.LeakyReLU(0.2, True),
            nn.Conv2d(512, 512, 4, stride=2, padding=1), nn.BatchNorm2d(512), nn.LeakyReLU(0.2, True),
        )
        self.decoder = nn.Sequential(
            nn.ConvTranspose2d(512, 512, 4, stride=2, padding=1), nn.BatchNorm2d(512), nn.ReLU(True),
            nn.ConvTranspose2d(512, 256, 4, stride=2, padding=1), nn.BatchNorm2d(256), nn.ReLU(True),
            nn.ConvTranspose2d(256, 128, 4, stride=2, padding=1), nn.BatchNorm2d(128), nn.ReLU(True),
            nn.ConvTranspose2d(128,  64, 4, stride=2, padding=1), nn.BatchNorm2d(64),  nn.ReLU(True),
            nn.ConvTranspose2d( 64,   3, 4, stride=2, padding=1), nn.Tanh()
        )
    def forward(self, x): return self.decoder(self.encoder(x))

print('Baseline CNN ready.')

# init models and optimizers

def weights_init(m):
    if isinstance(m, (nn.Conv2d, nn.ConvTranspose2d)):
        nn.init.normal_(m.weight.data, 0.0, 0.02)
    elif isinstance(m, nn.BatchNorm2d):
        nn.init.normal_(m.weight.data, 1.0, 0.02)
        nn.init.constant_(m.bias.data, 0)

G   = UNetGenerator().to(device);          G.apply(weights_init)
D   = PatchGANDiscriminator().to(device);  D.apply(weights_init)
CNN = BaselineCNN().to(device);            CNN.apply(weights_init)

criterion_GAN = nn.BCEWithLogitsLoss()
criterion_L1  = nn.L1Loss()

opt_G   = optim.Adam(G.parameters(),   lr=LR, betas=(BETA1, 0.999))
opt_D   = optim.Adam(D.parameters(),   lr=LR, betas=(BETA1, 0.999))
opt_CNN = optim.Adam(CNN.parameters(), lr=LR, betas=(BETA1, 0.999))

print(f'G params:   {sum(p.numel() for p in G.parameters()):,}')
print(f'D params:   {sum(p.numel() for p in D.parameters()):,}')
print(f'CNN params: {sum(p.numel() for p in CNN.parameters()):,}')

# training loop

history = {'G_loss':[], 'D_loss':[], 'G_adv':[], 'G_L1':[], 'CNN_loss':[]}

fixed_edges, fixed_reals = next(iter(val_loader))
fixed_edges = fixed_edges.to(device)
fixed_reals = fixed_reals.to(device)

def denorm(x):
    return (x * 0.5 + 0.5).clamp(0, 1)

def visualise(epoch):
    G.eval(); CNN.eval()
    with torch.no_grad():
        gan_out = G(fixed_edges)
        cnn_out = CNN(fixed_edges)
    fig, axes = plt.subplots(4, 4, figsize=(16, 16))
    for col, (title, imgs) in enumerate(zip(
        ['Edge Input', 'Ground Truth', 'Pix2Pix Output', 'Baseline CNN'],
        [fixed_edges, fixed_reals, gan_out, cnn_out]
    )):
        for row in range(4):
            img = denorm(imgs[row]).cpu().permute(1,2,0).numpy().clip(0,1)
            axes[row, col].imshow(img)
            if row == 0: axes[row, col].set_title(title, fontsize=11, fontweight='bold')
            axes[row, col].axis('off')
    plt.suptitle(f'Epoch {epoch}', fontsize=14, fontweight='bold')
    plt.tight_layout(); plt.show()
    G.train(); CNN.train()

print('Starting training...')
start = time.time()

for epoch in range(1, EPOCHS + 1):
    G.train(); D.train(); CNN.train()
    tot_G = tot_D = tot_adv = tot_l1 = tot_cnn = 0
    n = len(train_loader)

    for edges, reals in train_loader:
        edges = edges.to(device); reals = reals.to(device)

        real_lbl = torch.ones (D(edges, reals).shape, device=device)
        fake_lbl = torch.zeros(D(edges, reals).shape, device=device)

        # Discriminator
        opt_D.zero_grad()
        fakes = G(edges).detach()
        loss_D = 0.5 * (criterion_GAN(D(edges, reals), real_lbl) +
                         criterion_GAN(D(edges, fakes), fake_lbl))
        loss_D.backward(); opt_D.step()

        # Generator
        opt_G.zero_grad()
        fakes   = G(edges)
        l_adv   = criterion_GAN(D(edges, fakes), real_lbl)
        l_l1    = criterion_L1(fakes, reals) * LAMBDA_L1
        loss_G  = l_adv + l_l1
        loss_G.backward(); opt_G.step()

        # Baseline CNN
        opt_CNN.zero_grad()
        loss_cnn = criterion_L1(CNN(edges), reals)
        loss_cnn.backward(); opt_CNN.step()

        tot_G += loss_G.item(); tot_D += loss_D.item()
        tot_adv += l_adv.item(); tot_l1 += l_l1.item()
        tot_cnn += loss_cnn.item()

    history['G_loss'].append(tot_G/n); history['D_loss'].append(tot_D/n)
    history['G_adv'].append(tot_adv/n); history['G_L1'].append(tot_l1/n)
    history['CNN_loss'].append(tot_cnn/n)

    elapsed = (time.time()-start)/60
    eta     = elapsed/epoch * (EPOCHS-epoch)
    print(f'[{epoch:3d}/{EPOCHS}] G:{tot_G/n:.4f} D:{tot_D/n:.4f} '
          f'Adv:{tot_adv/n:.4f} L1:{tot_l1/n:.2f} CNN:{tot_cnn/n:.4f} '
          f'| {elapsed:.1f}m elapsed, ETA {eta:.1f}m')

    if epoch % 15 == 0 or epoch == 1 or epoch == 50:
        visualise(epoch)

print(f'\nTraining complete in {(time.time()-start)/60:.1f} min')

# loss curves

epochs = range(1, EPOCHS + 1)
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].plot(epochs, history['G_loss'], label='Generator',     color='royalblue', lw=2)
axes[0].plot(epochs, history['D_loss'], label='Discriminator', color='tomato',    lw=2)
axes[0].set_title('GAN Losses', fontweight='bold'); axes[0].legend(); axes[0].grid(alpha=0.3)
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Loss')

axes[1].plot(epochs, history['G_adv'], label='Adversarial',          color='darkorange',    lw=2)
axes[1].plot(epochs, [v/LAMBDA_L1 for v in history['G_L1']],
             label=f'L1 (÷{LAMBDA_L1:.0f})', color='mediumseagreen', lw=2)
axes[1].set_title('Generator Loss Components', fontweight='bold'); axes[1].legend(); axes[1].grid(alpha=0.3)
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Loss')

axes[2].plot(epochs, [v/LAMBDA_L1 for v in history['G_L1']],
             label='Pix2Pix L1 (÷100)', color='royalblue',  lw=2)
axes[2].plot(epochs, history['CNN_loss'],
             label='Baseline CNN L1',   color='firebrick',   lw=2, linestyle='--')
axes[2].set_title('Pix2Pix vs Baseline CNN', fontweight='bold'); axes[2].legend(); axes[2].grid(alpha=0.3)
axes[2].set_xlabel('Epoch'); axes[2].set_ylabel('L1 Loss')

plt.suptitle('Training Loss Tracking', fontsize=14, fontweight='bold')
plt.tight_layout(); plt.savefig('loss_curves.png', dpi=150); plt.show()

# comparison

G.eval(); CNN.eval()
test_edges, test_reals = next(iter(val_loader))
test_edges = test_edges.to(device); test_reals = test_reals.to(device)

with torch.no_grad():
    gan_preds = G(test_edges)
    cnn_preds = CNN(test_edges)

fig, axes = plt.subplots(4, 4, figsize=(18, 18))
titles = ['Edge Input', 'Ground Truth', 'Pix2Pix GAN', 'Baseline CNN']
imgs_list = [test_edges, test_reals, gan_preds, cnn_preds]

for row in range(4):
    for col in range(4):
        img = denorm(imgs_list[col][row]).cpu().permute(1,2,0).numpy().clip(0,1)
        axes[row, col].imshow(img)
        if row == 0: axes[row, col].set_title(titles[col], fontsize=13, fontweight='bold')
        axes[row, col].axis('off')

plt.suptitle('Final Visual Comparison: Pix2Pix vs Baseline CNN', fontsize=15, fontweight='bold')
plt.tight_layout(); plt.savefig('final_comparison.png', dpi=150); plt.show()

# ── Compute val metrics ─────────────────────────────────────────
G.eval(); CNN.eval()
gan_mae = cnn_mae = ssim_gan = ssim_cnn = 0
n_batches = 0

def compute_psnr(pred, target, max_val=1.0):
    mse = ((pred - target) ** 2).mean().item()
    return 10 * np.log10(max_val**2 / mse) if mse > 0 else float('inf')

gan_psnr_list, cnn_psnr_list = [], []

with torch.no_grad():
    for edges, reals in val_loader:
        edges = edges.to(device); reals = reals.to(device)
        g_out = G(edges); c_out = CNN(edges)

        # Denorm to [0,1] for metrics
        g_dn = denorm(g_out); c_dn = denorm(c_out); r_dn = denorm(reals)

        gan_mae += criterion_L1(g_out, reals).item()
        cnn_mae += criterion_L1(c_out, reals).item()
        gan_psnr_list.append(compute_psnr(g_dn, r_dn))
        cnn_psnr_list.append(compute_psnr(c_dn, r_dn))
        n_batches += 1

gan_mae /= n_batches; cnn_mae /= n_batches
gan_psnr = np.mean(gan_psnr_list); cnn_psnr = np.mean(cnn_psnr_list)

# ── Print Report ────────────────────────────────────────────────
sep = "=" * 60
print(sep)
print("           PIX2PIX GAN — TRAINING REPORT")
print(sep)

print("\n📌 MODEL PARAMETERS")
print(f"  U-Net Generator params    : {sum(p.numel() for p in G.parameters()):,}")
print(f"  PatchGAN Discriminator    : {sum(p.numel() for p in D.parameters()):,}")
print(f"  Baseline CNN params       : {sum(p.numel() for p in CNN.parameters()):,}")

print("\n📌 HYPERPARAMETERS")
print(f"  Image Size      : {IMG_SIZE} x {IMG_SIZE}")
print(f"  Batch Size      : {BATCH_SIZE}")
print(f"  Epochs          : {EPOCHS}")
print(f"  Learning Rate   : {LR}")
print(f"  Adam β1 / β2    : {BETA1} / 0.999")
print(f"  Lambda L1       : {LAMBDA_L1}")
print(f"  Train Samples   : {len(train_ds)}")
print(f"  Val Samples     : {len(val_ds)}")

print("\n📌 FINAL TRAINING LOSSES (last epoch)")
print(f"  Generator Total Loss      : {history['G_loss'][-1]:.4f}")
print(f"    ↳ Adversarial Component : {history['G_adv'][-1]:.4f}")
print(f"    ↳ L1 Component (×100)   : {history['G_L1'][-1]:.4f}")
print(f"  Discriminator Loss        : {history['D_loss'][-1]:.4f}")
print(f"  Baseline CNN L1 Loss      : {history['CNN_loss'][-1]:.4f}")

print("\n📌 LOSS PROGRESSION (every 10 epochs)")
print(f"  {'Epoch':>6} | {'G_Loss':>8} | {'D_Loss':>8} | {'G_Adv':>8} | {'G_L1':>8} | {'CNN_L1':>8}")
print("  " + "-"*55)
for i in range(0, EPOCHS, 10):
    print(f"  {i+1:>6} | {history['G_loss'][i]:>8.4f} | {history['D_loss'][i]:>8.4f} | "
          f"{history['G_adv'][i]:>8.4f} | {history['G_L1'][i]:>8.2f} | {history['CNN_loss'][i]:>8.4f}")
print(f"  {EPOCHS:>6} | {history['G_loss'][-1]:>8.4f} | {history['D_loss'][-1]:>8.4f} | "
      f"{history['G_adv'][-1]:>8.4f} | {history['G_L1'][-1]:>8.2f} | {history['CNN_loss'][-1]:>8.4f}")

print("\n📌 VALIDATION METRICS")
print(f"  {'Metric':<20} {'Pix2Pix GAN':>14} {'Baseline CNN':>14}")
print("  " + "-"*50)
print(f"  {'MAE (L1)':<20} {gan_mae:>14.4f} {cnn_mae:>14.4f}")
print(f"  {'PSNR (dB)':<20} {gan_psnr:>14.2f} {cnn_psnr:>14.2f}")
improvement_mae  = (cnn_mae  - gan_mae)  / cnn_mae  * 100
improvement_psnr = (gan_psnr - cnn_psnr) / cnn_psnr * 100
print(f"\n  MAE improvement  (Pix2Pix vs CNN): {improvement_mae:+.2f}%")
print(f"  PSNR improvement (Pix2Pix vs CNN): {improvement_psnr:+.2f}%")

print("\n📌 DISCRIMINATOR HEALTH CHECK")
final_d = history['D_loss'][-1]
print(f"  Final D loss: {final_d:.4f}  (ideal ≈ 0.5 = balanced equilibrium)")
if 0.3 < final_d < 0.7:
    print("  ✅ Healthy: Generator and Discriminator are in equilibrium")
elif final_d < 0.3:
    print("  ⚠️  D is winning — Generator may need more training or LR adjustment")
else:
    print("  ⚠️  G is winning — Discriminator may need stronger capacity")

print("\n" + sep)
print("  Outputs: loss_curves.png | final_comparison.png")
print(sep)